'use strict';
const $ = s => document.querySelector(s);
const icons = {
 box:'<path d="m3 7 9-5 9 5v10l-9 5-9-5V7Z"/><path d="m3 7 9 5 9-5M12 12v10M7.5 4.5l9 5"/>',
 battle:'<path d="m3 3 5 1 11 12-3 3L4 8 3 3ZM14 6l6-3-2 6M6 14l-3 6 6-2M14 20l6-6M4 14l6 6"/>',
 upgrade:'<path d="m7 10 5-6 5 6M12 4v13M5 17v4h14v-4"/>',
 gift:'<rect x="3" y="8" width="18" height="4" rx="1"/><path d="M5 12v9h14v-9M12 8v13"/><path d="M12 8H7a3 3 0 1 1 3-3l2 3Zm0 0h5a3 3 0 1 0-3-3l-2 3Z"/>',
 inventory:'<rect x="3" y="6" width="18" height="15" rx="2"/><path d="M8 6V3h8v3M3 12h18M10 12v3h4v-3"/>',
 flame:'<path d="M12 2c2 7-4 7-2 11 2 0 4-2 4-5 7 5 8 14-2 14C3 22 1 14 7 8c-1 5 2 5 2 5-2-5 2-7 3-11Z"/>',
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 back:'<path d="M20 12H4m6-6-6 6 6 6"/>',
 shield:'<path d="m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6l8-4Z"/><path d="m8 12 3 3 5-6"/>',
 check:'<path d="m5 12 4 4L20 5"/>',
 plus:'<path d="M12 4v16M4 12h16"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 trophy:'<path d="M7 3h10v7a5 5 0 0 1-10 0V3ZM7 5H3v3a4 4 0 0 0 4 4M17 5h4v3a4 4 0 0 1-4 4M12 15v6M8 21h8"/>'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.box}</svg>`;
const skins = [
 {id:0,weapon:'AK-47',name:'Asiimov',image:'ak-asiimov.png',value:48,color:'#f8667e',rarity:'Covert'},
 {id:1,weapon:'AWP',name:'Asiimov',image:'awp-asiimov.png',value:92,color:'#f8667e',rarity:'Covert'},
 {id:2,weapon:'AWP',name:'Dragon Lore',image:'awp-dragon-lore.png',value:1600,color:'#e7b85c',rarity:'Covert'},
 {id:3,weapon:'M4A4',name:'Howl',image:'m4-howl.png',value:900,color:'#e7b85c',rarity:'Contraband'},
 {id:4,weapon:'M4A4',name:'Desolate Space',image:'m4-desolate-space.png',value:24,color:'#bb78ed',rarity:'Classified'},
 {id:5,weapon:'USP-S',name:'Kill Confirmed',image:'usp-kill-confirmed.png',value:38,color:'#f8667e',rarity:'Covert'},
 {id:6,weapon:'Desert Eagle',name:'Printstream',image:'deagle-printstream.png',value:52,color:'#f8667e',rarity:'Covert'},
 {id:7,weapon:'★ Karambit',name:'Doppler · Phase 2',image:'knife-doppler.png',value:620,color:'#e7b85c',rarity:'Rare Special'}
];
const cases = [
 {id:'inferno',name:'Inferno',price:25,img:'case-1.png',accent:'#ff783e',label:'FAN FAVORITE',category:'popular',pool:[[4,44],[5,28],[0,18],[1,8],[7,2]]},
 {id:'neon',name:'Neon Dreams',price:12,img:'case-3.png',accent:'#bd8aff',label:'AFTER HOURS',category:'budget',pool:[[4,62],[5,25],[6,10],[1,3]]},
 {id:'asiimov',name:'Asiimov Protocol',price:49,img:'case-2.png',accent:'#ff9b64',label:'COMMUNITY PICK',category:'popular',pool:[[4,30],[0,40],[1,25],[7,5]]},
 {id:'prisma',name:'Prisma Rush',price:19,img:'case-4.png',accent:'#73c3fb',label:'COLOR OUTSIDE THE LINES',category:'budget',pool:[[4,55],[5,25],[6,15],[1,4],[7,1]]},
 {id:'knife',name:'Knife Party',price:149,img:'case-4.png',accent:'#e0b863',label:'HIGH STAKES',category:'premium',pool:[[4,40],[0,25],[1,20],[7,15]]},
 {id:'starter',name:'First Drop',price:5,img:'case-2.png',accent:'#92c98a',label:'START SOMETHING',category:'budget',pool:[[4,85],[5,10],[0,4],[6,1]]},
 {id:'redline',name:'Red Alert',price:39,img:'case-1.png',accent:'#f47180',label:'TURN UP THE HEAT',category:'popular',pool:[[4,35],[5,30],[0,22],[1,10],[3,3]]},
 {id:'vault',name:'The Vault',price:249,img:'case-3.png',accent:'#d2b876',label:'THE RARE COLLECTION',category:'premium',pool:[[0,45],[1,25],[7,20],[3,8],[2,2]]},
 {id:'print',name:'Monochrome',price:35,img:'case-2.png',accent:'#ccd1e4',label:'CLEAN BY DESIGN',category:'popular',pool:[[4,35],[5,25],[6,30],[1,9],[7,1]]},
 {id:'dragon',name:'Dragon’s Den',price:89,img:'case-4.png',accent:'#e3a25b',label:'CHASE THE LEGEND',category:'premium',pool:[[4,45],[0,27],[1,20],[7,6],[2,2]]}
];
const navItems = [['cases','box','Cases'],['battles','battle','Case Battles'],['upgrade','upgrade','Upgrader'],['daily','gift','Free Daily'],['inventory','inventory','My Inventory']];
const STORE='embercase-demo-v1';
const freshState=()=>({balance:1000,inventory:[],lastDaily:0,streak:0,opened:0});
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORE));if(!s || !Number.isFinite(s.balance) || s.balance<0 || !Array.isArray(s.inventory))return freshState();return {balance:s.balance,inventory:s.inventory.filter(i=>skins[i.skin] && typeof i.uid==='string'),lastDaily:Number(s.lastDaily)||0,streak:Number(s.streak)||0,opened:Number(s.opened)||0};}catch{return freshState();}}
let state=loadState(), route='cases', category='all', sort='featured', busy=false, sourceUid=null, targetId=null, multiplier=2, battleCase='inferno', battleRounds=3;
const number=n=>Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const credits=n=>`<span class="coin">◈</span> ${number(n)}`;
const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const asset=f=>window.EMBER_ASSETS?.[f] || `assets/${f}`;
function rng(){const data=new Uint32Array(1);crypto.getRandomValues(data);return data[0]/4294967296;}
function choose(pool){let roll=rng()*100;for(const [id,weight] of pool){roll-=weight;if(roll<0)return skins[id];}return skins[pool[pool.length-1][0]];}
function makeItem(s){return {uid:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${rng()}`,skin:s.id,created:Date.now()};}
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));}catch{toast('Browser storage is unavailable. Progress lasts for this visit only.',true);}updateBalance();}
function updateBalance(){$('#balance').textContent=number(state.balance);}
function toast(message,error=false){const el=document.createElement('div');el.className=`toast${error?' error':''}`;el.textContent=message;$('#toasts').append(el);setTimeout(()=>el.remove(),4300);}
function showModal(html){$('#modal-body').innerHTML=`<div class="modal-content"><button class="close-modal" data-action="close" aria-label="Close dialog" ${busy?'disabled':''}>×</button>${html}</div>`;if(!$('#modal').open)$('#modal').showModal();}
function closeModal(){if(busy)return;$('#modal').close();}
function addDrop(s){const track=$('#ticker');track.insertAdjacentHTML('afterbegin',dropCard(s,'You'));if(track.children.length>9)track.lastElementChild.remove();}
function dropCard(s,user){return `<div class="drop-item" style="--rarity:${s.color}"><img src="${asset(s.image)}" alt="${s.weapon} ${s.name}" width="95" height="49"><strong>${s.weapon} | ${s.name}</strong><small>${user}</small><span>◈ ${number(s.value)}</span></div>`;}
function renderNav(){const html=navItems.map(([id,ico,label])=>`${id==='inventory'?'<div class="nav-divider"></div>':''}<button class="nav-button ${route===id?'active':''}" data-nav="${id}" title="${label}" ${route===id?'aria-current="page"':''}>${icon(ico)}<span>${label}</span>${id==='daily'&&canClaim()?'<span class="nav-pill">FREE</span>':''}</button>`).join('');$('#main-nav').innerHTML=html;$('#mobile-nav').innerHTML=html;$('.side-daily strong').innerHTML=canClaim()?'Your daily drop<br>is waiting.':'A fresh drop.<br>Every 24 hours.';$('.side-daily button').innerHTML=canClaim()?'Claim your free case <span>↗</span>':'View daily reward <span>↗</span>';}
function setRouteHash(to){try{history.pushState(null,'',`#${to}`);}catch{location.hash=to;}}
function navigate(to,push=true){if(busy){toast('Let this round finish first.');return false;}if(!navItems.some(n=>n[0]===to)&&!to.startsWith('case/'))to='cases';route=to;if(push && location.hash.slice(1)!==to)setRouteHash(to);render();window.scrollTo({top:0,behavior:'instant'});return true;}
function render(){renderNav();updateBalance();if(route.startsWith('case/'))renderCase(route.split('/')[1]);else({cases:renderHome,daily:renderDaily,inventory:renderInventory,upgrade:renderUpgrade,battles:renderBattles}[route]||renderHome)();}
function caseCard(c){return `<article class="case-card" style="--accent:${c.accent}"><div class="case-label"><span>${c.label}</span><span>↗</span></div><a href="#case/${c.id}" data-case="${c.id}" aria-label="View ${c.name} case"><div class="case-image-wrap"><img src="${asset(c.img)}" alt="${c.name} weapon case" width="230" height="175" loading="eager"></div><h3>${c.name}</h3></a><p>${c.pool.length} possible drops</p><button class="price-button" data-case="${c.id}" aria-label="View ${c.name}, ${c.price} demo credits">${credits(c.price)}</button></article>`;}
function catalog(){let list=cases.filter(c=>category==='all'||c.category===category);if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);return list.map(caseCard).join('');}
function renderHome(){$('#main').innerHTML=`<section class="hero" aria-label="Featured cases"><div class="hero-main"><div class="hero-copy"><div class="hero-kicker"><span></span> THE INFERNO COLLECTION</div><h1>YOUR NEXT DROP.<br><em>YOUR NEXT LEVEL.</em></h1><p>A little risk. A legendary collection.</p><button class="primary" data-case="inferno">Explore Inferno ${icon('arrow')}</button></div><div class="hero-art"><img class="hero-weapon" src="${asset('ak-asiimov.png')}" alt="AK-47 Asiimov" width="480" height="360"></div></div><div class="daily-promo"><div class="eyebrow">ON THE HOUSE</div><h2>A NEW DAY.<br>A FREE DROP.</h2><p>Your daily case. Zero credits needed.</p>${icon('gift')}<button class="primary" data-nav="daily">${canClaim()?'Claim free case':'View daily reward'} ${icon('arrow')}</button></div></section><section aria-labelledby="cases-title"><div class="section-heading"><h2 id="cases-title">${icon('flame')} PICK YOUR NEXT CASE</h2><small>${cases.length} CASES. ENDLESS POSSIBILITIES.</small></div><div class="catalog-top"><div class="tabs" aria-label="Case categories">${[['all','All cases'],['popular','Popular'],['budget','Budget'],['premium','Premium']].map(([id,label])=>`<button class="tab ${category===id?'active':''}" data-category="${id}" aria-pressed="${category===id}">${label}</button>`).join('')}</div><select class="sort-select" id="sort" aria-label="Sort cases"><option value="featured" ${sort==='featured'?'selected':''}>Featured</option><option value="low" ${sort==='low'?'selected':''}>Price: low first</option><option value="high" ${sort==='high'?'selected':''}>Price: high first</option></select></div><div class="case-grid" id="catalog">${catalog()}</div><p class="catalog-note">${icon('shield')} Free play only. All prices and skins are virtual.</p></section><section class="battle-teaser">${icon('battle')}<div><h3>SAME CASES. ONE WINNER.</h3><p>Take on a bot. The highest total takes the drops.</p></div><button class="secondary" data-nav="battles">Enter case battles ↗</button></section>`;}
function skinCard(s,options={}){return `<${options.select?'button':'article'} class="skin-card ${options.select?'selectable':''} ${options.selected?'selected':''}" style="--rarity:${s.color}" ${options.select?`data-${options.select}="${options.uid??s.id}" aria-pressed="${!!options.selected}"`:''}><img src="${asset(s.image)}" alt="${s.weapon} ${s.name}" width="220" height="140" loading="eager"><strong>${s.weapon}</strong><span class="finish">${s.name}</span><div class="skin-meta"><b>◈ ${number(s.value)}</b><small>${options.odds!==undefined?`${options.odds}% chance`:s.rarity}</small></div>${options.sell?`<button class="sell-button" data-sell="${options.uid}">Sell for ◈ ${number(s.value)}</button>`:''}</${options.select?'button':'article'}>`;}
function renderCase(id){const c=cases.find(x=>x.id===id);if(!c){navigate('cases');return;}$('#main').innerHTML=`<button class="back" data-nav="cases">${icon('back')} Back to all cases</button><div class="view-header"><div><div class="eyebrow" style="color:${c.accent}">${c.label}</div><h1 class="view-title" style="margin-top:8px">${c.name}</h1></div><span class="stat-chip">CASE PRICE <strong>◈ ${number(c.price)}</strong></span></div><section class="case-stage"><img class="big-case" src="${asset(c.img)}" alt="${c.name} case"><div class="open-controls"><button class="primary" data-open="${c.id}" ${state.balance<c.price?'disabled':''}>Open case <span>◈ ${number(c.price)}</span></button></div><p class="odds-label">${state.balance<c.price?'Not enough credits. Use the + button to add free demo credits.':'One case. One drop. Added straight to your inventory.'}</p></section><div class="section-heading"><h2>POSSIBLE DROPS</h2><small>DEMO VALUES · EXACT DROP CHANCES</small></div><div class="skin-grid">${c.pool.map(([id,p])=>skinCard(skins[id],{odds:p})).join('')}</div>`;}
function canClaim(){return Date.now()-state.lastDaily>=86400000;}
function timeUntilDaily(){const ms=Math.max(0,state.lastDaily+86400000-Date.now());const secs=Math.ceil(ms/1000);return `${String(Math.floor(secs/3600)).padStart(2,'0')}:${String(Math.floor(secs/60)%60).padStart(2,'0')}:${String(secs%60).padStart(2,'0')}`;}
function renderDaily(){const eligible=canClaim();const day=eligible?(Date.now()-state.lastDaily>172800000?1:(state.streak%7)+1):((state.streak-1)%7)+1;$('#main').innerHTML=`<div class="view-header"><div><h1 class="view-title">GOOD THINGS COME DAILY.</h1><p class="view-description">Your daily reward. Always free.</p></div><span class="stat-chip">STREAK <strong>${state.streak} ${state.streak===1?'DAY':'DAYS'}</strong></span></div><section class="panel daily-main"><img class="daily-image" src="${asset('case-2.png')}" alt="Free daily case"><div class="daily-details"><div class="eyebrow" style="color:var(--green)">${eligible?'READY WHEN YOU ARE':'NICE DROP. SEE YOU TOMORROW.'}</div><h2>THE DAILY DROP</h2><p>One free skin and 100 demo credits. Come back every 24 hours to keep your streak going.</p><button class="primary" data-action="daily" ${eligible?'':'disabled'}>${icon(eligible?'gift':'clock')} ${eligible?'Open my free case':`Next drop in <span id="daily-timer">${timeUntilDaily()}</span>`}</button></div></section><div class="day-track">${Array.from({length:7},(_,i)=>`<div class="day-card ${day===i+1?'current':''}"><span>DAY ${i+1}</span>${icon(i+1===day&&!eligible?'check':'gift')}<strong>${i+1===day&&!eligible?'Claimed':'Skin + 100 ◈'}</strong></div>`).join('')}</div><p class="help-line">Each day has the same reward. Your streak is saved on this browser.</p><div class="section-heading" style="margin-top:35px"><h2>IN YOUR DAILY CASE</h2><small>ONE SKIN PER CLAIM</small></div><div class="skin-grid">${[[4,70],[5,20],[0,10]].map(([id,p])=>skinCard(skins[id],{odds:p})).join('')}</div>`;}
function renderInventory(){const total=state.inventory.reduce((sum,i)=>sum+skins[i.skin].value,0);$('#main').innerHTML=`<div class="view-header"><div><h1 class="view-title">YOUR COLLECTION</h1><p class="view-description">Keep it. Upgrade it. Or turn it into your next case.</p></div><span class="stat-chip">${state.inventory.length} SKINS <strong>◈ ${number(total)}</strong></span></div>${state.inventory.length?`<div class="skin-grid">${[...state.inventory].reverse().map(i=>skinCard(skins[i.skin],{sell:true,uid:i.uid})).join('')}</div><p class="help-line">Selling gives you demo credits. These virtual skins cannot be traded or withdrawn.</p>`:`<div class="empty">${icon('inventory')}<h3>Every collection starts with one drop.</h3><p>Open a case or claim your free daily skin to get started.</p><button class="primary" data-nav="daily">Claim your free drop ${icon('arrow')}</button></div>`}`;}
function openCase(id){if(busy)return;const c=cases.find(x=>x.id===id);if(!c || state.balance<c.price){toast('Add some free demo credits to open this case.',true);return;}const winner=choose(c.pool),item=makeItem(winner);state.balance-=c.price;state.inventory.push(item);state.opened++;save();animateOpening(c.name,c.pool,winner,item);}
function claimDaily(){if(busy || !canClaim()){toast('Your next daily case is not ready yet.',true);return;}const pool=[[4,70],[5,20],[0,10]],winner=choose(pool),item=makeItem(winner);state.streak=Date.now()-state.lastDaily>172800000?1:state.streak+1;state.lastDaily=Date.now();state.balance+=100;state.inventory.push(item);state.opened++;save();animateOpening('Daily Drop',pool,winner,item,'Plus 100 demo credits. See you tomorrow.');}
function animateOpening(name,pool,winner,item,extra='Your new skin is waiting in your inventory.'){
 busy=true;
 showModal(`<div class="eyebrow" style="color:var(--orange)">OPENING ${name.toUpperCase()}</div><h2 id="modal-title">LET IT ROLL.</h2><div class="roulette-window"><div class="roulette-pointer"></div><div class="roulette-strip" id="reel"></div></div><p class="roll-status">Finding your next favorite…</p><p class="fineprint">Your drop is already saved, even if you leave this page.</p>`);
 const count=45,winIndex=36;let entries=Array.from({length:count},()=>choose(pool));entries[winIndex]=winner;
 $('#reel').innerHTML=entries.map(s=>`<div class="roulette-item" style="--rarity:${s.color}"><img src="${asset(s.image)}" alt=""><strong>${s.weapon}</strong><span>${s.name}</span></div>`).join('');
 const reel=$('#reel');reel.style.transform='translateX(-72.5px)';
 const duration=reduced()?80:5100,offset=winIndex*150+72.5+(rng()-.5)*65;
 sounds.unlock();let lastReelTick=-1;const spinStart=performance.now();function reelTick(now){const progress=Math.min(1,(now-spinStart)/duration),step=Math.floor((1-Math.pow(1-progress,4))*36);if(step!==lastReelTick){sounds.tick();lastReelTick=step;}if(progress<1)requestAnimationFrame(reelTick);}requestAnimationFrame(reelTick);
 const animation=reel.animate([{transform:'translateX(-72.5px)'},{transform:`translateX(-${offset}px)`}],{duration,easing:'cubic-bezier(.12,.68,.08,1)',fill:'forwards'});
 animation.finished.then(()=>{const landed=reel.children[winIndex];landed.classList.add('landed');$('.roll-status').textContent='That one is yours.';setTimeout(()=>{busy=false;addDrop(winner);render();showResult(winner,item,extra);},reduced()?50:750);});
}
function showResult(s,item,extra){sounds.drop(s);showModal(`<div class="result-label">${icon('check')} ADDED TO YOUR INVENTORY</div><h2 id="modal-title">${s.weapon} | ${s.name}</h2><img class="result-skin" src="${asset(s.image)}" alt="${s.weapon} ${s.name}"><strong style="font-size:1.5rem">${credits(s.value)}</strong><p>${extra}</p><div class="result-actions"><button class="secondary" data-sell-result="${item.uid}">Sell for ${number(s.value)} ◈</button><button class="primary" data-action="keep">Keep skin ${icon('check')}</button></div>`);}
function sellItem(uid,fromModal=false){if(busy)return;const i=state.inventory.findIndex(i=>i.uid===uid);if(i<0){toast('This skin is no longer in your inventory.',true);return;}const skin=skins[state.inventory[i].skin];state.inventory.splice(i,1);state.balance+=skin.value;if(sourceUid===uid){sourceUid=null;targetId=null;}save();if(fromModal)closeModal();render();toast(`${skin.weapon} sold for ${number(skin.value)} demo credits.`);}
function getUpgradeSource(){return state.inventory.find(i=>i.uid===sourceUid);}
function getUpgradeChance(){const item=getUpgradeSource();return item&&targetId!==null&&skins[targetId]?UpgradeEngine.chance(skins[item.skin].value,skins[targetId].value):0;}
function pickMultiplier(n){multiplier=n;const item=getUpgradeSource();if(item){const source=skins[item.skin];const opts=skins.filter(s=>UpgradeEngine.eligible(source.value,s.value)).sort((a,b)=>Math.abs(a.value-source.value*n)-Math.abs(b.value-source.value*n));targetId=opts[0]?.id??null;}renderUpgrade();}
function selectSource(uid){const item=state.inventory.find(i=>i.uid===uid);if(!item)return;sourceUid=uid;multiplier=0;if(targetId!==null&&!UpgradeEngine.eligible(skins[item.skin].value,skins[targetId].value))targetId=null;renderUpgrade();}
function selectTarget(id){const item=getUpgradeSource();if(!item){toast('Choose an inventory skin first.');return;}if(!skins[id]||!UpgradeEngine.eligible(skins[item.skin].value,skins[id].value)){toast('Choose a target worth at least 1.00 credit more.',true);return;}targetId=id;multiplier=0;renderUpgrade();}
function renderUpgrade(){
 const item=getUpgradeSource(),source=item?skins[item.skin]:null,target=targetId!==null?skins[targetId]:null,chance=getUpgradeChance();
 const targets=skins.filter(s=>!source||UpgradeEngine.eligible(source.value,s.value)).sort((a,b)=>a.value-b.value);
 $('#main').innerHTML=`<div class="view-header"><div><h1 class="view-title">AIM A LITTLE HIGHER.</h1><p class="view-description">Choose any eligible skin. The price ratio is your chance.</p></div><span class="stat-chip">◈ 1.00 = US$1.00 <strong>DEMO</strong></span></div>
 <section class="upgrade-arena" id="upgrade-arena"><div class="upgrade-slot">${source?`<img src="${asset(source.image)}" alt="${source.weapon} ${source.name}"><strong>${source.weapon} | ${source.name}</strong><p>◈ ${number(source.value)} · US$${number(source.value)}</p>`:`${icon('plus')}<strong>Your skin</strong><p>Select from your inventory below</p>`}</div>
 <div class="upgrade-center"><div class="chance-ring" style="--chance:${chance}%"><div class="spin-pointer" id="upgrade-pointer"><i></i></div><div class="chance-inner">${icon('upgrade')}<strong>${chance.toFixed(2)}<span style="font:500 1.2rem var(--display)">%</span></strong><span id="upgrade-status">SUCCESS CHANCE</span></div></div><div class="multiplier-group">${[2,3,5].map(n=>`<button class="multiplier ${n===multiplier?'active':''}" data-multiplier="${n}" aria-pressed="${n===multiplier}" ${source?'':'disabled'}>${n}×</button>`).join('')}</div><button class="primary" data-action="upgrade" ${chance?'':'disabled'}>Spin upgrade ${icon('upgrade')}</button><p class="spin-legend"><span></span> Land on orange to win</p></div>
 <div class="upgrade-slot">${target?`<img src="${asset(target.image)}" alt="${target.weapon} ${target.name}"><strong>${target.weapon} | ${target.name}</strong><p>◈ ${number(target.value)} · US$${number(target.value)}</p>`:`${icon('plus')}<strong>Your target</strong><p>At least ◈ 1.00 more than your skin</p>`}</div></section>
 <div class="upgrade-rules"><strong>No house reduction.</strong> ${chance?`${number(source.value)} ÷ ${number(target.value)} × 100 = <b>${chance.toFixed(2)}%</b>.`:'50 → 100 credits = 50% success. 50 → 200 = 25%.'} Each spin is independent; wins are not guaranteed.</div>
 <div class="two-column"><section><div class="column-title">YOUR INVENTORY <span class="muted">${state.inventory.length} ${state.inventory.length===1?'skin':'skins'}</span></div>${state.inventory.length?`<div class="skin-grid">${state.inventory.map(i=>skinCard(skins[i.skin],{select:'source',uid:i.uid,selected:i.uid===sourceUid})).join('')}</div>`:`<div class="empty">${icon('inventory')}<h3>Start with a skin.</h3><p>Claim a free daily drop for your first upgrade.</p><button class="secondary" data-nav="daily">Get a free skin</button></div>`}</section>
 <section><div class="column-title">ALL ELIGIBLE SKINS <span class="muted">${source?`${targets.length} targets · min. ◈ ${number(source.value+1)}`:'Select your skin first'}</span></div><div class="skin-grid">${targets.map(s=>skinCard(s,{select:source?'target':undefined,selected:targetId===s.id})).join('')||'<div class="empty"><p>No skin in this catalog is worth at least 1 credit more.</p></div>'}</div></section></div><p class="help-line">Win: your selected skin is replaced by the target. Fail: only your selected skin is consumed. 1 credit = US$1 in demo valuation; credits cannot be cashed out. Odds are rounded to two decimals and the displayed number is used for the draw.</p>`;
}
function upgrade(){
 const item=getUpgradeSource(),chance=getUpgradeChance();if(busy||!item||!chance)return;
 const source=skins[item.skin],target=skins[targetId],result=UpgradeEngine.resolve(source.value,target.value,rng());
 busy=true;sounds.unlock();const newItem=result.success?makeItem(target):null;
 state.inventory=state.inventory.filter(i=>i.uid!==item.uid);if(newItem)state.inventory.push(newItem);save();
 const arena=$('#upgrade-arena'),pointer=$('#upgrade-pointer');arena.classList.add('is-spinning');$('#upgrade-status').textContent='SPINNING…';
 document.querySelectorAll('#main button').forEach(b=>b.disabled=true);
 const rotation=360*6+result.angle,duration=reduced()?100:4400,start=performance.now();let lastTick=-1;
 function frame(now){const t=Math.min(1,(now-start)/duration),eased=1-Math.pow(1-t,4),angle=rotation*eased;pointer.style.transform=`rotate(${angle}deg)`;const tick=Math.floor(angle/30);if(tick!==lastTick){sounds.tick();lastTick=tick;}if(t<1){requestAnimationFrame(frame);return;}
   $('#upgrade-status').textContent=result.success?'SUCCESS':'FAILED';arena.classList.remove('is-spinning');arena.classList.add(result.success?'upgrade-won':'upgrade-lost');
   if(result.success)sounds.success();else sounds.fail();
   setTimeout(()=>{busy=false;sourceUid=null;targetId=null;renderUpgrade();const details=`Roll: ${result.roll.toFixed(4)} / 100. Success range: 0–${chance.toFixed(2)} (upper bound excluded).`;
     if(result.success){addDrop(target);showResult(target,newItem,`Upgrade successful. ${details}`);}else{showModal(`<div class="eyebrow" style="color:var(--red)">UPGRADE UNSUCCESSFUL</div><h2 id="modal-title">THIS ONE SLIPPED AWAY.</h2><p>Your selected skin was consumed. ${details}</p><button class="primary" data-action="close">Back to upgrader</button>`);}
   },reduced()?100:900);
 }
 requestAnimationFrame(frame);
}

function renderBattles(){const c=cases.find(c=>c.id===battleCase);$('#main').innerHTML=`<div class="view-header"><div><h1 class="view-title">CASE BATTLES</h1><p class="view-description">Same cases. Same odds. The higher total wins every drop.</p></div><span class="stat-chip">YOU VS. BOT</span></div><div class="battle-config"><section class="panel"><label class="field-label">01 — Choose your case</label><div class="battle-case-picker">${cases.slice(0,6).map(c=>`<button class="battle-case-option ${c.id===battleCase?'active':''}" data-battle-case="${c.id}" aria-pressed="${c.id===battleCase}"><img src="${asset(c.img)}" alt=""><strong>${c.name}</strong><small>◈ ${number(c.price)}</small></button>`).join('')}</div><div class="field-label" style="margin-top:26px">02 — Number of rounds</div><div class="battle-options">${[1,3,5].map(n=>`<button data-rounds="${n}" class="${battleRounds===n?'active':''}" aria-pressed="${battleRounds===n}">${n} ${n===1?'round':'rounds'}</button>`).join('')}</div><p class="help-line">Each player opens one case per round. If totals tie, you keep your own drops.</p></section><section class="panel battle-summary"><div class="eyebrow" style="color:var(--orange)">YOUR MATCH</div><h2>${c.name.toUpperCase()} SHOWDOWN</h2><div class="battle-matchup"><div><div class="player-circle">JD</div><strong>You</strong></div><span class="versus">VS</span><div><div class="player-circle bot-circle">${icon('battle')}</div><strong>Ember Bot</strong></div></div><div class="battle-total"><span>${battleRounds} × ${c.name}</span><strong>◈ ${number(c.price*battleRounds)}</strong></div><button class="primary full-width" data-action="battle" ${state.balance<c.price*battleRounds?'disabled':''}>Start battle ${icon('battle')}</button><p class="help-line">${state.balance<c.price*battleRounds?'Add free demo credits using the + button to play.':'Your entry covers your cases. The bot has its own virtual entry.'}</p></section></div>`;}
function startBattle(){const c=cases.find(c=>c.id===battleCase),cost=c.price*battleRounds;if(busy||state.balance<cost)return;busy=true;const mine=Array.from({length:battleRounds},()=>choose(c.pool)),theirs=Array.from({length:battleRounds},()=>choose(c.pool));const myTotal=mine.reduce((a,s)=>a+s.value,0),theirTotal=theirs.reduce((a,s)=>a+s.value,0);state.balance-=cost;const result=myTotal>theirTotal?'win':myTotal===theirTotal?'tie':'loss';const awards=result==='win'?[...mine,...theirs]:result==='tie'?mine:[];state.inventory.push(...awards.map(makeItem));state.opened+=battleRounds;save();let round=0;$('#main').innerHTML=`<section class="battle-stage"><div class="eyebrow" style="color:var(--orange)">${c.name.toUpperCase()} SHOWDOWN</div><h2 id="round-label">GET READY.</h2><p class="muted" style="font-size:.85rem">${battleRounds} ${battleRounds===1?'round':'rounds'} · ◈ ${number(cost)} entry</p><div class="battle-players"><div class="panel battle-player" id="my-side"><h3>YOU</h3><strong id="my-score">◈ 0.00</strong><div class="skin-grid" id="my-drops"></div></div><div class="panel battle-player" id="bot-side"><h3>EMBER BOT</h3><strong id="bot-score">◈ 0.00</strong><div class="skin-grid" id="bot-drops"></div></div></div><div id="battle-result" aria-live="polite"></div></section>`;
 const reveal=()=>{const s=mine[round],b=theirs[round];sounds.drop(s);sounds.drop(b,.25);$('#round-label').textContent=`ROUND ${round+1} OF ${battleRounds}`;$('#my-drops').insertAdjacentHTML('afterbegin',skinCard(s));$('#bot-drops').insertAdjacentHTML('afterbegin',skinCard(b));for(const node of [$('#my-drops').firstElementChild,$('#bot-drops').firstElementChild])node.animate([{opacity:0,transform:'translateY(20px) scale(.97)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:reduced()?0:600,easing:'cubic-bezier(.2,.8,.2,1)'});round++;$('#my-score').textContent=`◈ ${number(mine.slice(0,round).reduce((a,s)=>a+s.value,0))}`;$('#bot-score').textContent=`◈ ${number(theirs.slice(0,round).reduce((a,s)=>a+s.value,0))}`;if(round<battleRounds)setTimeout(reveal,reduced()?70:1400);else setTimeout(()=>{busy=false;$('#round-label').textContent='BATTLE COMPLETE';if(result!=='tie')$(result==='win'?'#my-side':'#bot-side').classList.add('winner');$('#battle-result').innerHTML=`<div class="battle-result"><h2>${result==='win'?'THE DROPS ARE YOURS.':result==='tie'?'A PERFECT TIE.':'EMBER BOT TAKES THIS ONE.'}</h2><p>${result==='win'?`${awards.length} skins worth ${number(myTotal+theirTotal)} credits were added to your inventory.`:result==='tie'?'Your own drops were added to your inventory.':'The bot had the higher total. No skins were added to your inventory.'}</p><button class="primary" data-nav="battles">New battle</button> <button class="secondary" data-nav="inventory">My inventory</button></div>`;awards.slice(0,2).forEach(addDrop);},reduced()?70:600);};setTimeout(reveal,reduced()?70:900);
}
function wallet(){showModal(`<div class="eyebrow" style="color:var(--orange)">YOUR DEMO WALLET</div><h2 id="modal-title">KEEP THE GOOD DROPS COMING.</h2><div class="wallet-amount">◈ ${number(state.balance)}</div><p>Add 1,000 free credits to explore every case and battle. No payment required.</p><button class="primary full-width" data-action="add-credits">Add 1,000 free credits ${icon('plus')}</button><p class="fineprint">1 credit = US$1 in demo valuation. Credits have no cash value and cannot be withdrawn.</p>`);}
function about(){showModal(`<h2 id="modal-title">WELCOME TO EMBERCASE.</h2><p>An independent CS2 case-opening concept inspired by the genre. Everything here runs on free virtual credits.</p><ul class="modal-list"><li>Open cases and keep or sell your virtual drops.</li><li>Claim a free daily skin and 100 credits every 24 hours.</li><li>Upgrade a skin with the displayed success chance.</li><li>Challenge a bot in 1, 3 or 5-round battles.</li></ul><p class="fineprint">Progress is saved on this browser only. There are no payments, Steam trades, real skins or cash withdrawals. Values are fictional demo values. Not affiliated with Hellcase or Valve. Game artwork belongs to its respective owners.</p><button class="primary" data-action="close">Let’s play ${icon('arrow')}</button>`);}
function odds(){showModal(`<h2 id="modal-title">KNOW YOUR DROP.</h2><p>Each case shows its exact item probabilities before you open it. Every opening makes a new independent random draw.</p><div class="odds-row"><span>Case opening</span><strong>Weighted item odds</strong></div><div class="odds-row"><span>Daily case</span><strong>70% / 20% / 10%</strong></div><div class="odds-row"><span>Case battles</span><strong>Same odds for both players</strong></div><p>In the upgrader, the source-to-target value ratio determines your displayed chance, with no house reduction: source value ÷ target value × 100, rounded to two decimals. Any catalog target worth at least 1.00 credit more is eligible.</p><p class="fineprint">Random draws happen in your browser. This is an entertainment demo, not an audited real-money system.</p><button class="primary" data-action="close">Got it</button>`);}
document.addEventListener('click',e=>{
 const el=e.target.closest('button,a');if(!el)return;
 if(el.dataset.action==='sound'){sounds.toggle();return;}sounds.unlock();
 if(el.dataset.nav){e.preventDefault();if(navigate(el.dataset.nav))closeModal();return;}
 if(el.dataset.case){e.preventDefault();navigate(`case/${el.dataset.case}`);return;}
 if(el.dataset.category){category=el.dataset.category;renderHome();return;}
 if(el.dataset.open){openCase(el.dataset.open);return;}
 if(el.dataset.sell){sellItem(el.dataset.sell);return;}
 if(el.dataset.sellResult){sellItem(el.dataset.sellResult,true);return;}
 if(busy && el.dataset.action!=='close')return;
 if(el.dataset.source){selectSource(el.dataset.source);return;}
 if(el.dataset.target!==undefined){selectTarget(Number(el.dataset.target));return;}
 if(el.dataset.multiplier){pickMultiplier(Number(el.dataset.multiplier));return;}
 if(el.dataset.battleCase){battleCase=el.dataset.battleCase;renderBattles();return;}
 if(el.dataset.rounds){battleRounds=Number(el.dataset.rounds);renderBattles();return;}
 switch(el.dataset.action){case'close':closeModal();break;case'keep':closeModal();toast('Skin kept in your inventory.');break;case'daily':claimDaily();break;case'upgrade':upgrade();break;case'battle':startBattle();break;case'credits':wallet();break;case'add-credits':state.balance+=1000;save();closeModal();render();toast('1,000 free demo credits added.');break;case'about':about();break;case'odds':odds();break;}
});
document.addEventListener('change',e=>{if(e.target.id==='sort'){sort=e.target.value;$('#catalog').innerHTML=catalog();}});
$('#modal').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal();});
window.addEventListener('popstate',()=>{if(busy){setRouteHash(route);return;}navigate(location.hash.slice(1)||'cases',false);});
window.addEventListener('hashchange',()=>{if(!busy)navigate(location.hash.slice(1)||'cases',false);});
window.addEventListener('storage',e=>{if(e.key===STORE&&!busy){state=loadState();render();}});
setInterval(()=>{if(route==='daily' && $('#daily-timer')){if(canClaim())renderDaily();else $('#daily-timer').textContent=timeUntilDaily();}},1000);
$('#ticker').innerHTML=[skins[7],skins[0],skins[6],skins[1],skins[4],skins[3],skins[5],skins[2]].map((s,i)=>dropCard(s,['Ember Bot','Demo player','Ember Bot','Demo player'][i%4])).join('');
navigate(location.hash.slice(1)||'cases',false);
function registerTools(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(ctx.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'read_demo_collection',title:'Read demo collection',description:'Read the virtual credit balance, owned skins and daily reward availability.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input&&Object.keys(input).length)throw new Error('No arguments expected.');return {balance:state.balance,inventory:state.inventory.map(i=>({id:i.uid,weapon:skins[i.skin].weapon,skin:skins[i.skin].name,value:skins[i.skin].value})),dailyAvailable:canClaim()};}});register({name:'navigate_demo_section',title:'Open a demo section',description:'Navigate to cases, daily rewards, inventory, the upgrader or bot battles. Does not open a case or spend credits.',inputSchema:{type:'object',properties:{section:{type:'string',enum:['cases','daily','inventory','upgrade','battles']}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='section')||!navItems.some(n=>n[0]===input.section))throw new Error('Choose a valid section.');if(busy)throw new Error('Wait for the current round to finish.');navigate(input.section);return {section:route};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
registerTools();
sounds.update();
